# Generated by Django 5.2 on 2025-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0001_alter_businesssettings_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='daily_order_number',
            field=models.IntegerField(default=0, help_text='Daily order number that resets after end day'),
        ),
    ]
