# Generated by Django 5.2 on 2025-05-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_order_daily_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Unique reference number with format PB plus 4 digits', max_length=10, null=True),
        ),
    ]
