# Generated by Django 4.2.20 on 2025-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),  # Add dependency on auth app
        ('posapp', '0003_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.RunSQL(
            # Using two separate statements to avoid the FROM clause issue
            """
            CREATE TEMPORARY TABLE duplicate_emails AS
            SELECT email
            FROM auth_user
            GROUP BY email
            HAVING COUNT(*) > 1;
            
            UPDATE auth_user
            SET email = CONCAT(email, '-', id)
            WHERE email IN (SELECT email FROM duplicate_emails);
            
            DROP TEMPORARY TABLE duplicate_emails;
            """,
            # No reverse SQL needed for the update
            None
        ),
        migrations.RunSQL(
            # Add unique constraint after handling duplicates
            """
            ALTER TABLE auth_user
            ADD CONSTRAINT auth_user_email_key UNIQUE (email);
            """,
            # Reverse SQL to remove the constraint if needed
            """
            ALTER TABLE auth_user
            DROP CONSTRAINT IF EXISTS auth_user_email_key;
            """
        ),
    ]
