# Generated by Django 5.0.2 on 2025-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0012_businesslogo_remove_order_amount_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My POS Business', max_length=255)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_rate_card', models.DecimalField(decimal_places=2, default=5.0, help_text='Tax rate for card payments in percentage', max_digits=5)),
                ('tax_rate_cash', models.DecimalField(decimal_places=2, default=15.0, help_text='Tax rate for cash payments in percentage', max_digits=5)),
                ('currency_symbol', models.CharField(default='Rs.', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
