# Generated by Django 5.2 on 2025-05-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0014_orderitem_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_running_item',
            field=models.BooleanField(default=False, help_text='Indicates this is a running item with unlimited stock'),
        ),
    ]
