# Generated by Django 5.2 on 2025-05-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0015_product_is_running_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_running_item',
        ),
    ]
