# Generated by Django 5.2 on 2025-05-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0022_alter_product_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
    ]
