# Generated by Django 5.2 on 2025-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0023_remove_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, help_text="For manual discounts, this will be 'MANUAL'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, help_text="'percentage' or 'fixed' for manual discounts", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Value of the manual discount', max_digits=10, null=True),
        ),
    ]
