# Generated by Django 5.2 on 2025-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0024_order_discount_code_order_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_code',
            field=models.CharField(blank=True, default='', help_text="For manual discounts, this will be 'MANUAL'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(blank=True, default='fixed', help_text="'percentage' or 'fixed' for manual discounts", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Value of the manual discount', max_digits=10, null=True),
        ),
    ]
