# Generated by Django 5.0.2 on 2025-05-07 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0027_advanceadjustment_billadjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billadjustment',
            name='bill_image',
        ),
        migrations.AlterField(
            model_name='advanceadjustment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, help_text='Date of advance (automatically set to today)'),
        ),
        migrations.CreateModel(
            name='BillAdjustmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Picture of the bill', upload_to='bill_adjustments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posapp.billadjustment')),
            ],
        ),
    ]
