# Generated by Django 5.2 on 2025-05-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', 'convert_billadjustment_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='business_name',
            field=models.CharField(default='PickBug Solutions', max_length=255),
        ),
    ]
