# Generated by Django 5.2 on 2025-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0003_order_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(help_text='Internal system reference (not displayed to users)', max_length=50, unique=True),
        ),
    ]
