# Generated by Django 5.2 on 2025-05-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service charges amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charges_percent',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Service charges percent applied if subtotal > 1000', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='table_no',
            field=models.CharField(blank=True, help_text='Table number for dine-in orders', max_length=20, null=True),
        ),
    ]
