# Generated by Django 5.2 on 2025-05-13 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0005_order_service_charges_order_service_charges_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_charges',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_charges_percent',
        ),
        migrations.RemoveField(
            model_name='order',
            name='table_no',
        ),
    ]
