# Generated by Django 4.2.20 on 2025-04-03 13:11

from django.db import migrations, models


def handle_duplicate_discount_codes(apps, schema_editor):
    Discount = apps.get_model('posapp', 'Discount')
    
    # Get all discounts with their codes
    discounts = Discount.objects.all()
    
    # Dictionary to track seen codes
    seen_codes = {}
    
    # Loop through discounts and modify duplicates
    for discount in discounts:
        code = discount.code
        
        # Skip if no code (null or empty)
        if not code:
            continue
            
        # If we've seen this code before, make it unique
        if code in seen_codes:
            seen_codes[code] += 1
            # Append a number to make it unique
            discount.code = f"{code}-{seen_codes[code]}"
            discount.save()
        else:
            seen_codes[code] = 1


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_auto_20250403_1200'),
    ]

    operations = [
        # First run our custom function to handle duplicates
        migrations.RunPython(
            handle_duplicate_discount_codes,
            # No reverse operation needed
            migrations.RunPython.noop
        ),
        # Then add the unique constraint
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        # Also include these other changes from migration 0005
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
