# Generated by Django 5.2 on 2025-05-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0007_order_delivery_address_order_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(blank=True, help_text='Table number for dine-in orders', null=True),
        ),
        migrations.CreateModel(
            name='TableStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('occupied_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_status', to='posapp.order')),
            ],
        ),
    ]
