# Generated by Django 5.2 on 2025-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0008_order_table_number_tablestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_number',
        ),
        migrations.DeleteModel(
            name='TableStatus',
        ),
    ]
