# Generated by Django 5.0.2 on 2025-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0013_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='Indicates if this item is temporary and not yet saved'),
        ),
    ]
