# Generated by Django 5.2 on 2025-05-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0016_remove_product_is_running_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='running_item',
            field=models.BooleanField(default=False, help_text='If checked, stock will not decrease when ordered'),
        ),
    ]
