# Generated by Django 5.2 on 2025-05-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0017_product_running_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text="Products can only be deleted if they're not in pending orders", on_delete=django.db.models.deletion.PROTECT, to='posapp.product'),
        ),
    ]
