# Generated by Django 5.2 on 2025-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0018_update_orderitem_product_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='If checked, product is archived and hidden from active listings'),
        ),
    ]
