# Generated by Django 5.2 on 2025-05-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0019_product_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_quantity',
            field=models.IntegerField(blank=True, help_text='Original quantity for tracking stock adjustments', null=True),
        ),
    ]
