# Generated by Django 5.2 on 2025-05-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0020_orderitem_original_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Unique numeric identifier for the product', max_length=20, null=True, unique=True),
        ),
    ]
