# Generated by Django 5.2 on 2025-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0021_remove_product_cost_price_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default='000000', help_text='Unique numeric identifier for the product', max_length=20, unique=True),
        ),
    ]
