# Generated by Django 5.0.2 on 2025-05-07 18:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0026_add_branch_manager_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person or entity', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Advance amount', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of advance')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the adjustment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person or entity', max_length=255)),
                ('quantity', models.IntegerField(help_text='Quantity of items')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price amount', max_digits=10)),
                ('bill_image', models.ImageField(blank=True, help_text='Picture of the bill', null=True, upload_to='bill_adjustments/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the adjustment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
