# Generated by Django 5.0.2 on 2025-05-08 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0028_remove_billadjustment_bill_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billadjustment',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Total bill amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='billadjustment',
            name='quantity',
            field=models.IntegerField(blank=True, help_text='Quantity of items (optional)', null=True),
        ),
        migrations.CreateModel(
            name='EndDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the day was ended')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about ending the day', null=True)),
                ('ended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
