# Generated by Django 5.2 on 2025-05-09 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0029_alter_billadjustment_price_and_more'),
        ('posapp', 'convert_images_to_db'),
    ]

    operations = [
    ]
