from .auth_views import *
from .dashboard_views import *
from .user_views import *
from .category_views import *
from .product_views import *
from .order_views import *
from .discount_views import *
from .settings_views import *
from .reports_views import * 